
# Ethical clearance

All research conducted by staff and students must be in accordance with the ethical principles and codes set out by the British Psychological Society. [These guidelines can be found here](https://www.bps.org.uk/sites/bps.org.uk/files/Policy/Policy%20-%20Files/BPS%20Code%20of%20Human%20Research%20Ethics.pdf).

All students must have ethical clearance before starting on the empirical component of their project. This rule applies to ALL projects, including, for example, projects which use archived data and modelling projects. Failure to obtain ethical clearance will lead to a zero being awarded in both project modules.

The Ethics form is completed online on the School Ethics system, linked to from this page <https://www.psy.plymouth.ac.uk/Home/>. 

Login to complete your study details and upload your brief and debrief documents and then submit the form electronically. Your supervisor will review and approve your form, or return it to you for correction and resubmission. Once they have approved it you will received a confirmation email and then your form will be passed to the School Ethics committee. If you have selected that you need special equipment on the Technical page, the confirmation email will also invite you to come talk to the Tech Office to discuss what you need

When submitting your project you must include a statement about the ethical issues involved in your project (see section on handing in your project).

Students must comply with the BPS and Plymouth University ethical guidelines not only in principle but also in practice. If complaints are received about the way a student conducts his or her project then, after a fair investigation, this may lead to marks being deducted.

Please note that there are special requirements when dealing with outside agencies. These include: research on NHS trust property (or involving patient participants recruited by NHS professionals but seen – or otherwise engaged – at other locations) must be given ethical clearance from the NHS – called the Local Ethics Research Committee; when working with children there must be a DBS check in place (organised by The Faculty Compliance Team, 4th Floor Rolle building), and there must either be positive permission from parents, or negative permission but with a fail-safe method of communicating with parents. For other agencies (e.g., police, prisons, companies etc), it is necessary to comply with the ethical procedures of these organisations. Research activities conducted off-campus should comply with Plymouth University Health & Safety guidelines and with those of any external agencies involved.