# Supervision

## What can the student expect from the supervisor?

The research idea often comes from the supervisor. The research design (i.e., how that idea is tested) is arrived at through discussion and is central to the project. Although students may have an initial idea for a design, many students do not, at the end of the second year, have the experience to develop a good design. The supervisor is responsible for giving the student a frank assessment of the quality and scope of the student’s suggested design and providing guidance about alternatives if necessary. It is important to recognise that students vary in their ambition, and the advice given to students by supervisors should be appropriate to the student’s ambition. The supervisor is also expected to provide advice about likely practical problems that may affect choice of projects (e.g., difficulties with ethical clearance from external bodies), and ensure that the work load is appropriate (see above).

Once the overall design is settled, the student may then have to work on details of the methodology, again following advice as appropriate by the supervisor. The supervisor signs the ethics form, but the form is completed by the student.

The student will be responsible for carrying out a literature search – the supervisor may provide some guidance but should not provide the student with a full list of references.

The student should collect the data in a manner agreed with the supervisor.

Once the data have been collected, the student should analyse and interpret the data with advice as determined by the supervisor. There is often confusion about the amount of help that can be given by the supervisor, and the situation is made more complex by the great variety of projects. However, here are some pointers for staff and students alike:

The student and supervisor should discuss the analysis options, and the supervisor is responsible for ensuring that the student has made a sensible choice about analysis. The supervisor can provide tutorial advice about statistical and other procedures. In some cases, supervisors carry out the analysis on their own computer as a way of showing the student what is done, and then the student goes away and does it by him or herself. However, the supervisor should not carry out the statistical analysis – this must be carried out by the student after advice has been given.

The student then writes up the project, and the supervisor should respond to direct questions about options in the write up. Supervisors should not read drafts but can read a write-up summary document submitted by the student and give verbal feedback in a meeting to discuss it (see the section on Feedback).

It is commonly the case that the amount of time and assistance required by the student varies over the course of the project and varies between students. More advice is usually needed towards the beginning of a project, but a maximum amount of supervision per week is estimated at 20 minutes – though sometimes more when students are supervised in groups. Once the student is running the project then supervision may be minimal in some cases but not invariably so. Advice should only be sought when it is needed but students should expect to have regular (weekly) contact (virtual or face-to-face meetings and email) with their supervisor.

The supervisor will give some advice about literature searching to be carried out by the student. The supervisor can give advice about the overall structure of the write up, and respond to specific queries of the student. However, because the project is a piece of assessment, the supervisor may not read and correct the project for the student – though should respond to specific queries about it (i.e., be reactive rather than proactive).

Inevitably, there is some variation in the amount of advice given by supervisors, because some students are unable to operate without directive information. If a student needs an extraordinary level of support, then this will be taken into account in the marking process. If you are concerned that you are getting too much or too little advice, then discuss this with your supervisor. Open communication to address potential differences of expectation or understanding is encouraged. If needed, you can talk to the module leader about this.

Supervisors vary in the way they like to supervise students (e.g., some prefer to use emails, some direct contact, some use group advice etc), and students should establish at the outset what pattern of supervision is expected. Supervisors of linked projects may suggest group meetings, but it is up to the discretion of the supervisor how to do this. However, students should feel that direct queries are being answered appropriately and within a reasonable time frame. Under normal circumstances a student should be able to see the supervisor within 7 days and receive email replies within 48 hours.

Project write-ups should be modelled on the structure on a journal article appropriate to the topic area. This structure can vary between topics and methods (e.g. qualitative versus quantitative). For most projects, there is a limit of 7 pages for the Introduction and 5 pages for the Discussion. There is no limit for the method and results sections. For some qualitative projects (e.g. discursive studies), it is appropriate to merge the results and discussion and there is a word limit of 16 pages on the combined section, including quotations and extracts, plus 4 pages for conclusions (use the standard format in use for essays). Supervisors must give their specific approval if this non-standard format is to be used. Supervisors may not extend the page limits.

A project should therefore appear like a rather lengthy journal article, with all the conventions of writing found in a published article. It may be obvious but a good way to see what a good project looks like is to read journal articles!

## What can the supervisor expect from the student?

Staff time is under considerable pressure, and students are expected to use staff supervision time efficiently, turning up to meetings as arranged, and preparing for meetings so as to use the time effectively etc. Good students show an ability to seek advice when advice is needed and use that advice effectively. Good students know when and how to seek advice.

Good students are active agents. That is, they are motivated to do things by themselves! When they need help, they ask for it. They don’t wait to be helped. The consequence is that the supervisor is often able to take a reactive role – i.e., reacting to specific queries by the student. Remember that the project has both an educational and an assessment objective. You will not be penalised for asking sensible questions.

When marking, supervisors take into account the conduct of the student. Students are not penalised for asking for advice. On the contrary, seeking appropriate advice is the hallmark of a good student. Marks may, however, be deducted if a student exhibits over-dependence or an inability to carry out advice given. The supervisor is responsible for informing the student if the student is behaving in an overly dependent fashion.

## Can students ask other members of staff for project advice?

The simple answer to this question is no unless the approach to another member of staff is made by the supervisor.

The exception to the above rule occurs where a student has a complaint about a supervisor (see later) when they can contact the project leader directly. However, the project leader cannot be used as a substitute for your supervisor when your supervisor is away.


## What happens if a student feels dissatisfied with their supervision?

Students and supervisors should both read the sections above on expectations. They should meet early and regularly and establish the method of communication to the satisfaction of all at the outset. This requires students to be engaged and proactive early in the project. If a student feels unhappy about some aspect of their supervision, they should try to talk to their supervisor about it at the earliest opportunity to resolve the matter collaboratively. Don’t leave doing this too late - problems are solved much more easily the earlier they are addressed. If this is not possible or is ineffective, then they should contact the project coordinator by email in the first instance, explaining the main grounds for complaint. Alternatively, they could contact their personal tutor. Issues of supervision can only be resolved if the supervisor is aware of them. It is best that this comes direct and early from the student. This clear communication of expectations ensures that the great majority of projects proceed smoothly, although there are challenges and obstacles to be overcome along the way. There is a formal University complaint procedure by which complaints can be made by students if their attempts to resolve matters directly, or via the projects coordinator or personal tutor have been unsuccessful (see elsewhere in this handbook).

Keeping a research diary throughout the course of your project work is good practice, and will also help in resolving any disagreements or other difficulties.

If you wish to discuss your supervision in confidence then please contact the module leader, Matt Roser ([matt.roser\@plymouth.ac.uk](mailto:matt.roser@plymouth.ac.uk)).