# Assessment
## How are the projects marked?

The project module counts for 40 credits. The project is marked by the supervisor and another member of staff, moderated by the project coordinator and externally reviewed by the external examiner.

The marking of projects takes into account the fact that projects come in various forms. For example, the structure of a qualitative project is different from a quantitative project. Equally, the work carried out for archival or modelling research is different. The two types of mark reflect this diversity.

Typically, the marking is carried out separately for a) the abstract, introduction and discussion sections and b) the method and results sections and the conduct of the project. These two marks will be collated into the final project mark by each of the two markers, who will then meet to discuss their impressions and marks and settle on one final mark for the entire report.

## Feedback

Feedback on all aspects of your research should be available in discussion with your supervisor. For instance, providing them with a summary of your project as you understand it, and talking through this summary with them in your first meetings, discussing and deciding on practical matters (such as the experimental design and timeline for research milestones), and regular guidance by email or in meetings **\- all constitute feedback.**

A feedback session in which you can discuss a written summary and bullet-point plan of your report with your supervisor will be held in the **week commencing 3rd March**. Further details and guidelines will be communicated closer to that time, but the aim is for all students to provide their supervisor with a two-page summary of their work, encompassing the research background, question and rationale, methods, results, and points of discussion including the implications of results for the research question. Your supervisor will give you verbal feedback in a meeting to discuss this skeleton plan of your report, which you should be writing by this time. This will help you to know that you have focused and organized your writing to present the correct information in the correct way with plenty of time to make amendments if needed.

Your presentation in Semester 2 will function in a similar way. In your second presentation you will need to cover all aspects of your research – the background, question, methods, results, and their implications. Supervisors and students should aim to hold their presentations in the **week commencing 17th March** . You can obtain immediate verbal feedback from your supervisor at that time or meet separately with them afterward if you want to do this without other students present.

The final report marks are posted after the last Stage 4 exam. After the final marks have been posted, if you think it may be beneficial to you, you may contact your supervisor to discuss feedback on your report.