# Recruiting participants

## Use of the SONA participant pool

The School uses an online system of experimental participation called SONA. This system will be used for both student and staff experiments. Each student receives an allocation of 40 points to use for recruitment via SONA. Each point is worth half an hour of participant time. Participants will be both first and second year students. In cases where you leave recruitment until very late in the academic year you may find it hard to find students and use your points, so we recommend recruiting participants as early as possible.

The time allotted to each participant should include meeting your participant, giving them any practice trials and fully debriefing them. Therefore if your study takes about 15 minutes to run, you will probably need at least 30 minutes to meet participants and later to debrief them after they have finished, as well as time to get yourself ready for your next participant. If your experiment takes half an hour of actual running time, you will need to allow more time than this between participants, and you will have to give your participants more than one participation point as it is essential that you properly introduce them to the study and debrief them. The number of points to which you will be entitled will be notified early in the first semester.

The procedure for using the pool, in outline, is as follows (more of the details will be given to you at the start of the academic year):

| Step 1 | Make sure you have obtained ethical clearance to run your study. You will be informed by the Senior Programme Administrator via e-mail when you have this clearance. You should note that starting to collect data for your study without ethical clearance will result in a mark of zero for both the component modules of the project. |
|---------|-----------------------------------------------------------|
| Step 2 | Organise rooms for testing. This should be done through the technical office, and needs to be done first, because you can’t advertise your study unless you can tell participants where and when the study will be held. Note that the system itself does not automatically book rooms, you have to do this yourself. |
| Step 3 | You will be able to enter details into the on-line system even before you get ethical clearance and the study is made ‘live’ on the system. You should include all the details asked for by the system, which will include (at least) the title of the study, information about the study, your contact details, and location and times of the study. Provide as much information as you can, but you must not do anything to suggest that your experiment is shorter than the allotted time. For example, if the study takes less than half an hour then you must advertise it as a half-hour experiment, if it takes more than half an hour but less than an hour then you must advertise it as lasting for one hour (and you must give two points) and so on. If you are using the on-line system, then this information can be logged and processed automatically. Once you have done this, and after you have ethical clearance, email your supervisor, who will check the study agrees with what you said in your ethics application. The supervisor then clicks the button on the study page "Request Approval", which sends a request to make the study visible. |
| Step 4 | The electronic system should send reminders automatically to your participants. There are rules about what happens if they (or you) fail to turn up, which are as follows. Cancellation of participation must be done by 4pm the day before the timeslot - this may be less than 24 hours if the study is the next morning. If a participant does not give you this notice, then they do not get any points and you are able to use their points for someone else. If you do not turn up to an experiment that you are scheduled to run, then you have to give the participant the point anyway. Any disputes on this matter should be referred to the [participation point co-ordinator](mailto:sonadmin.psy@plymouth.ac.uk). The on-line system should contain the information necessary to resolve any disputes. |
| Step 5 | Ensure that each participant reads and signs the Participation Consent Form *before* taking part in your experiment. The Participation Consent Form must be signed by all participants taking part in your experiment whether they receive participation points or not. |
| Step 6 | Carry out your experiment in conformity with the guidelines specified by the British Psychological Society regarding informed consent, debriefing, etc. |
| Step 7 | Once your participant has completed the study, enter this into the on-line system, which will record that you have used the point(s) and that the named participant has received it (them). Online studies can be configured to award points automatically. |
| Step 8 | When you have completed your experiment, sign the Participation Consent Form to certify its authenticity and include it in your project report. |

## Recruiting participants outside SONA

You may use participants outside of the pool provided you have gained the necessary ethical permissions and clearances. You are not permitted to pay subjects in order to get them to participate in your project.
