# Technical support

The Technical Office is in Link 109. There is a hatch and a bell you can ring to request support.

## Requesting assistance

The technical page of the Ethics website allows you to request technical assistance and support. The technical staff can provide assistance with any technical aspect of your data gathering including producing custom software for testing participants, and providing particular hardware requirements. This sheet must be completed by all students whether or not technical support is required.

To request technical assistance you need to fill in an additional form giving precise details of what you require. This has to be countersigned by your supervisor. You can submit this whilst you are waiting for ethical clearance, but the tech office can not start work on your project until ethics approval has been received. It is worth discussing your requirements as soon as you hand in your ethics form as work is dealt with on a first come first served basis.

When planning your project timescale remember to allow time to pilot your study properly to ensure it works as you require - you should use friends or colleagues to do this in the same conditions as your live participants. If using technical support you will be asked by your technician to complete a sign-off form before you start data gathering.

## Booking Laboratories

All lab space is booked through the [technical office website](https://psy.plymouth.ac.uk). If you are using specialist facilities provided by your supervisor then you need to make sure that your supervisor has block booked the facility and if you are collecting keycards through the tech office that they have been informed of your entitlement to use the room.

During term time rooms can only be booked for either the morning or the afternoon. All keycards must be returned between 12:30 and 12:45. Please note that the access to link block closes at 17:00 and you must schedule all testing to finish by 16:30 (16:00 on Fridays) in order to return the key before the tech office closes at 5pm (16:30 on Fridays).

## Booking Equipment

The Technical Office holds a wide range of equipment which you can book for use on your project. All equipment must be collected and signed for in person, and you must provide a contact number. Late return of equipment will incur a penalty.

## Assistance with problems

Please report all faults to the Technical Staff in the Technical Office. If you have a problem with a piece of borrowed equipment please do mention it when you return it - even if you think it was your fault we are not going to blame you, and would rather know about it before the next person takes it out.

Any mains powered equipment which you bring onto university premises for use with other people (participants) must be 'PAT' tested and certified. Use of untested equipment means that you are uninsured.

You must not move any University or School equipment between rooms without informing the Technical Office.