# Using psychological tests and questionnaires

It may be that your project involves the use of a questionnaire and/or a psychological test of some kind. It is highly probable that something along the lines you require is already in existence. Below are some sources that you may wish to explore to see if this is indeed the case.

## The following sources are available in the University Library:

Streiner D L & Norman G R (1991): *Health Measurement Scales: A Practical Guide to their Development and Use*. Oxford: Oxford University Press.

Goldman B A & Busch J C (1974 - 1985): *Directory of Unpublished Experimental Mental Measures Vols. 1 - 4.* New York: Human Sciences Press.

Robinson J P, Shaver P R & Wrightsman L S (1991): *Measures of Personality Social and Psychological Attitudes*. San Diego: Academic Press.

McDowell L & Newell C (1987): *Measuring Health: A Guide to Rating Scales and Questionnaires.* Oxford: Oxford University Press.

## The following Websites also help to locate tests:

American Psychological Association: A list of test-related topics

<http://www.apa.org/science/testing.html>
   
   The Buros Institute site - information about tests

<http://www.unl.edu/buros/>
   
   Some computerised tests (a selection).

<http://www.shrinktank.com/>
   
   Finally, the School of Psychology Test Library is available to final year students looking to use tests for their report and is free of charge. The library consists of around 400 tests and scales and is housed in the Link 305. The list of tests available can be checked on-line at <https://www.psy.plymouth.ac.uk/PsychometricTests/> If you cannot find the test you are looking for or want to change the format of a test and are not sure about how tests are protected by copyright laws, ask the Information Assistant for advice.